# arxivの学問領域の指定
subject: 'cat:math.IT' OR 'cat:math.ST' OR 'cat:cs.CR' OR 'cat:stat.ML' OR 'cat:stat.TH'

# 検索キーワード
keywords:
        privacy: 3
        utility: 2
        privacy-utility trade-off: 10
        decision theory: 3
        value of information: 4
        differential privacy: 5
        information leakage: 3
        information theoretical: 3
        information theory: 3
        

# 通知の閾値
score_threshold: 5
