# arxivの学問領域の指定
subject: 'cat:math.IT' OR 'cat:math.ST' OR 'cat:cs.CR' OR 'cat:stat.ML' OR 'cat:stat.TH'

# 検索キーワード
keywords:
        kaggle: 3
        resnet: 3
        anomaly detection: 1

# 通知の閾値
score_threshold: 0
